# Use official Node.js Alpine image
FROM node:alpine

# Set environment variables
ENV MONGO_INITDB_ROOT_USERNAME=admin \
    MONGO_INITDB_ROOT_PASSWORD=123

# Set working directory
WORKDIR /testapp

# Copy application files
COPY . .

# Install dependencies (if package.json exists)
RUN if [ -f package.json ]; then npm install; fi

# Expose the port your app runs on
EXPOSE 5500  
# Run the application
CMD ["node", "server.js"]
